#ifndef OBJECTTAGS_H
#define OBJECTTAGS_H
enum ObjectTag{
    OT_BOX,
    OT_FALLINGBOX,
    OT_TERRAINTYPESENDMARKERTAG,
    OT_BATBOT,
    OT_BIRD,
    OT_CHARACTER,
    OT_FROG,
    OT_GLOWBEING,
    OT_MYSTICALDOOR,
    OT_PLANT,
    OT_ENTITYTYPESENDMARKERTAG
};

#endif // OBJECTTAGS_H

